Added kwargs to Excel UI process beads table.
taborlab/FlowCal pull request #223
Opened 2016-12-11 21:34 UTC by JS3xton

See #222.

2016-12-11 21:44 UTC, JS3xton commented
As of e1111cf, all unit tests pass:

```
> python -m unittest discover
........................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 280 tests in 5.213s

OK
```

Tested manually and was able to turn off subpopulation selection step:
```python
FlowCal.excel_ui.process_beads_table(beads_table, instrument_table, plot=True)
```
yielded:
![populations_fl3_b1](https://cloud.githubusercontent.com/assets/2179825/21083529/2277c504-bfb8-11e6-9964-315becdd75dd.png)

```python
FlowCal.excel_ui.process_beads_table(beads_table, instrument_table, plot=True, get_transform_fxn_kwargs={'selection_fxn':None})
```
yielded:
![populations_fl3_b1](https://cloud.githubusercontent.com/assets/2179825/21083555/7018d24e-bfb8-11e6-8e23-49aacab49475.png)

(FL3 channel; top peak was being explicitly excluded in the input XLSX sheet)

2017-01-03 02:24 UTC, castillohair commented
Just to confirm, there are two peaks to the right being excluded in the second plot of your example. Are you explicitly excluding both?

2017-01-03 02:29 UTC, JS3xton commented
Yep. This should be the `Beads` tab of the XLSX sheet for that plot:

![excel_ui](https://cloud.githubusercontent.com/assets/2179825/21598892/0a5bb2ae-d12a-11e6-8a43-546c1d94fd7c.png)

2017-01-03 02:33 UTC, castillohair requested changes
The order of parameters is the only complain I have.

2017-01-03 02:33 UTC, castillohair commented on FlowCal/excel_ui.py
> +                        get_transform_fxn_kwargs={},
I think this should be the last parameter. This is such an edge case that I don't think changing the order of parameters is appropriate.

2017-01-03 02:56 UTC, JS3xton reviewed
updated as per your request

2017-01-03 03:26 UTC, merged