feat: add channel_labels
taborlab/FlowCal pull request #323
Opened 2020-03-09 09:47 UTC by abawchen

Add `channel_labels` and pass unittest.

2020-03-09 09:48 UTC, abawchen commented
@castillohair @JS3xton : Please help review this one, thanks.

2020-04-26 22:46 UTC, JS3xton requested changes
Thanks for the contribution. I found some small things, but otherwise looks good to me.

1) The `channel_labels` method should be described in the `FCSData` docstring.
2) It would be nice to explicitly unit test `channel_labels` like other similar methods (e.g. the [TestFCSAttributesDetectorVoltage](https://github.com/taborlab/FlowCal/blob/9cd83ef7fadf235e548bc6c1bb5ed22d4dde8416/test/test_io.py#L1584) class in `/test/test_io.py`).

2020-05-02 22:32 UTC, JS3xton commented
3. Add `channel_labels` method to [`TestFCSDataPickle`](https://github.com/taborlab/FlowCal/blob/9cd83ef7fadf235e548bc6c1bb5ed22d4dde8416/test/test_io.py#L2690) in `/test/test_io.py`.

2020-05-04 02:28 UTC, abawchen commented
@JS3xton : Thanks for feedback, I will update accordingly.

2020-05-05 05:08 UTC, abawchen commented
@JS3xton : I have a quick question, since all of the current testing fcs files don't have the channel value, i.e. they don't have `$PnS` key, it will return `[None, None, ..., None]` of all channels -- should I modify the current testing fcs file or create another one?

2020-05-05 15:54 UTC, JS3xton commented
> @JS3xton : I have a quick question, because all of the current testing fcs files don't have label value, i.e. they don't have `$PnS` key, and will return `[None, None, ..., None]` of all channels -- should I modify the current testing fcs file or create another one?

@abawchen Hmm, good point. I wouldn't modify the existing files. If you have a new file you can contribute, that seems fine to me. Otherwise, you might be able to find one in this repository: https://flowrepository.org/id/FR-FCM-ZZZ4.

2020-06-13 18:37 UTC, castillohair commented
@JS3xton , I added the description of `channel_labels` into the `FCSData` docstring. I also added it to the `TestFCSDataPickle` test.

@abawchen I think we would still prefer if you could incorporate an FCS file that actually contains `$PnS` keys and make unit tests for it. Code looks good, but we still have no "experimental" evidence that it does what it's supposed to do.

2020-10-26 14:11 UTC, abawchen commented
@JS3xton @castillohair :
Hi, thanks your feedback, although it's been a while 😅 
I have added `Data005.fcs` and add corresponding test case as you suggested, please help check it.

2020-10-29 16:03 UTC, castillohair commented on test/test_io.py
> +        - Data001.fcs: [None, None, None, None, None, None]
The last element of this list should be `'Time (204.80 sec.)'`. This is what you have later in the `test_attribute()` function.

2020-10-29 16:06 UTC, castillohair commented
In my opinion, the proposed unit tests validate that the feature works as expected. I have one observation in the test class docstring though. @JS3xton see what you think.

2020-10-29 23:14 UTC, JS3xton approved these changes

2020-10-29 23:17 UTC, JS3xton commented
Looks good to me.

(The new data file is kinda large, though... ~16MB)

2020-11-09 23:52 UTC, merged

2020-11-09 23:52 UTC, castillohair commented
@abawchen thanks for the contribution! We will release it with the new FlowCal version soon.